baseURL: "https://decodeai.in"
title: Manohar's Blog
paginate: 5
theme: ["hugo-notice", "PaperMod"] # Modified/Updated feature/hugo-notice tip by manohar on OCT 30 14:47 PM

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Manohar's Blog
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["https://s2.loli.net/2022/02/13/LQZurKxEpmwolbD.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicons/favicon.ico"
    favicon16x16: "favicons/favicon-16x16.png"
    favicon32x32: "favicons/favicon-32x32.png"
    apple_touch_icon: "favicons/apple-touch-icon.png"
    safari_pinned_tab: "favicons/android-chrome-192x192.png"

  label:
    text: "Home"
    icon: favicons/apple-touch-icon.png
    iconHeight: 50

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: false # hide everywhere but not in structured data
  #   hiddenInList: false # hide on list pages and home
  #   hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

    # for search
  # https://fusejs.io/api/options.html
outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]



menu:
  main:
    - name: Search Archives
      url: archives/
      weight: 5
    - name: Tags
      url: tags/
      weight: 10
    - name: Categories
      url: categories/
      weight: 15
    - name: About
      url: about/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
