name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

  # just for logging the Repo name and branch
      - name: Log Repo
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Log Branch
        run: echo " current branch  is ${{ github.ref }} "

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MLDECODER }}
          repository-name: ml-decoder/ml-decoder.github.io
          publish_dir: ./public
          publish_branch: main
